### PR TITLE
Las point return filter

### PR DESCRIPTION
**Pull request by terrycain**
Added two arguments "first_return_only" and "last_return_only" which will only include the points from a LiDAR file if they are the first or last return (they are mutually exclusive). This helps when trying to make a DSM, you can make a DTM if you assume the last return is always the ground (not the top of a building).

Added some more point record lengths so now the las reader supports from 0 to 5, doing 6-10 would require some work as the offsets to things change as in LAS1.4 the sizes of some fields change.

Also fixed 3 some compiler warnings on the unit tests as it was comparing signed ints to unsigned ones.

### CODE REVIEW

**Comment by hobu** [comment]
Thanks for the awesome pull request!

Do you have any idea why the tests are failing (thanks for the tests too, btw) on Travis?  They are passing for me locally with your branch.

**Comment by terrycain** [comment]
They are failing as we are leaking ~4GB of ram, travis kills after 3. Have squashed most of the bugs, there's one left I'm looking into but should be done soon.

**Comment by hobu** [comment]
ok, I appreciate the effort. I have given you push access to the repository so you can get done what you need.

**Comment by terrycain** [comment]
All tests passed. Shall proceed with a merge.

**Pull request merged**
